theme: jekyll-theme-minimal
title: "Attention Economy"
description: "A research journal.

*Subjects*: social media, online platforms, and big tech.

*Themes*: market competition, content moderation, and user privacy.

*Aims*: a coherent framework, pragmatic policy positions"